# fly.toml app configuration file generated for aicodecalc on 2025-01-12T15:06:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aicodecalc'
primary_region = 'lax'

[build]
  builder = 'heroku/builder:22'
  [build.args]
    NODE_VERSION = "20"

[processes]
  app = "sh -c 'npm run build && npx serve dist'"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
